[2024-10-25T23:18:26.481+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-25T23:18:26.516+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: indices_argentina_v02.load scheduled__2024-10-23T00:00:00+00:00 [queued]>
[2024-10-25T23:18:26.538+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: indices_argentina_v02.load scheduled__2024-10-23T00:00:00+00:00 [queued]>
[2024-10-25T23:18:26.538+0000] {taskinstance.py:2865} INFO - Starting attempt 12 of 17
[2024-10-25T23:18:26.568+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load> on 2024-10-23 00:00:00+00:00
[2024-10-25T23:18:26.577+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-25T23:18:26.584+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'indices_argentina_v02', 'load', 'scheduled__2024-10-23T00:00:00+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpxcxxxhym']
[2024-10-25T23:18:26.587+0000] {standard_task_runner.py:105} INFO - Job 141: Subtask load
[2024-10-25T23:18:26.591+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=15796) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-25T23:18:26.592+0000] {standard_task_runner.py:72} INFO - Started process 16018 to run task
[2024-10-25T23:18:26.685+0000] {task_command.py:467} INFO - Running <TaskInstance: indices_argentina_v02.load scheduled__2024-10-23T00:00:00+00:00 [running]> on host d9df5aecafce
[2024-10-25T23:18:27.051+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rolo' AIRFLOW_CTX_DAG_ID='indices_argentina_v02' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-23T00:00:00+00:00'
[2024-10-25T23:18:27.052+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-25T23:18:35.550+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-25T23:18:35.569+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: indices_argentina_v02.load scheduled__2024-10-23T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2024-10-25T23:18:35.569+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: indices_argentina_v02.load scheduled__2024-10-23T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2024-10-25T23:18:35.582+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
[2024-10-25T23:20:27.888+0000] {local_task_job_runner.py:318} WARNING - Recorded pid 16825 does not match the current pid 16018
[2024-10-25T23:20:27.891+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2024-10-25T23:20:32.939+0000] {local_task_job_runner.py:318} WARNING - Recorded pid 16825 does not match the current pid 16018
[2024-10-25T23:20:32.940+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2024-10-25T23:20:58.191+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-10-25T23:20:58.192+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-25T23:20:58.195+0000] {process_utils.py:132} INFO - Sending 15 to group 16018. PIDs of all processes in the group: [16018]
[2024-10-25T23:20:58.195+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 16018
[2024-10-25T23:20:58.197+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-10-25T23:20:58.229+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-25T23:20:58.257+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=16018, status='terminated', exitcode=0, started='23:18:26') (16018) terminated with exit code 0
