[2024-11-02T01:19:30.468+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-02T01:19:30.489+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: banco_mundial_indicators_v02.transform scheduled__2024-10-31T00:00:00+00:00 [queued]>
[2024-11-02T01:19:30.500+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: banco_mundial_indicators_v02.transform scheduled__2024-10-31T00:00:00+00:00 [queued]>
[2024-11-02T01:19:30.501+0000] {taskinstance.py:2865} INFO - Starting attempt 4 of 9
[2024-11-02T01:19:30.517+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform> on 2024-10-31 00:00:00+00:00
[2024-11-02T01:19:30.527+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'banco_mundial_indicators_v02', 'transform', 'scheduled__2024-10-31T00:00:00+00:00', '--job-id', '437', '--raw', '--subdir', 'DAGS_FOLDER/banco_mundial_indicators_dag.py', '--cfg-path', '/tmp/tmpbn4q81a4']
[2024-11-02T01:19:30.530+0000] {standard_task_runner.py:105} INFO - Job 437: Subtask transform
[2024-11-02T01:19:30.533+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2914) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-02T01:19:30.534+0000] {standard_task_runner.py:72} INFO - Started process 2915 to run task
[2024-11-02T01:19:30.584+0000] {task_command.py:467} INFO - Running <TaskInstance: banco_mundial_indicators_v02.transform scheduled__2024-10-31T00:00:00+00:00 [running]> on host 276004bbea2b
[2024-11-02T01:19:30.850+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rolo' AIRFLOW_CTX_DAG_ID='banco_mundial_indicators_v02' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-10-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-31T00:00:00+00:00'
[2024-11-02T01:19:30.851+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-02T01:19:41.889+0000] {logging_mixin.py:190} INFO - Error: list index out of range
[2024-11-02T01:19:43.004+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-02T01:19:43.017+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-02T01:19:43.017+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=banco_mundial_indicators_v02, task_id=transform, run_id=scheduled__2024-10-31T00:00:00+00:00, execution_date=20241031T000000, start_date=20241102T011930, end_date=20241102T011943
[2024-11-02T01:19:43.059+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-02T01:19:43.091+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-02T01:19:43.093+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
